ordering:
  homepage:
    header-1-default: ''
    header-2: ''
    header-3: ''
  sliders:
    revolution: ''
    rs-slideshow: ''
    particle: ''
  pages:
    -
      contact-us: ''
      about-us: ''
      portfolio-1:
        portfolio-1-3-columns: ''
        portfolio-1-4-columns: ''
        portfolio-1-grey-bg: ''
      portfolio-2:
        portfolio-2-3-columns: ''
        portfolio-2-4-columns: ''
    -
      pricing: ''
      faq: ''
      category-blog:
        news: ''
        services: ''
        portfolio: ''
      single-article: ''
    -
      single-article-left-sidebar: ''
      search-results: ''
      member-login: ''
      user-profile: ''
    -
      registration-form: ''
      username-reminder: ''
      password-reset: ''
      2015-10-16-15-34-59: ''
  features:
    module-positions: ''
    menu-editor: ''
    particles: ''
    uikit-framework: ''
    scrollreveal-js: ''
    module-variations: ''
    typography: ''
    2015-10-19-14-05-19: ''
  2015-10-17-18-38-09:
    2015-10-19-10-26-50: ''
    2015-10-19-10-27-29: ''
    2015-10-19-10-28-00: ''
    2015-10-19-10-28-30: ''
    2015-10-19-10-28-57: ''
    2015-10-19-10-29-22: ''
  __particle-KjbCK: ''
  __particle-GWhqM: ''
items:
  homepage:
    id: 101
    hash: ''
    dropdown_hide: '0'
    width: auto
    class: ''
  pages:
    id: 150
    hash: ''
    dropdown: fullwidth
    dropdown_hide: '0'
    width: auto
    class: ''
    columns:
      - 25
      - 25
      - 25
      - 25
  pages/category-blog:
    id: 162
    hash: ''
    dropdown_hide: '0'
    width: auto
    class: ''
  features:
    id: 183
    columns:
      - 100
  2015-10-17-18-38-09:
    id: 184
    hash: ''
    dropdown_hide: ''
    width: auto
    class: presets-demo
  2015-10-17-18-38-09/2015-10-19-10-26-50:
    id: 185
    hash: ''
    dropdown_hide: ''
    width: auto
    class: preset1
  2015-10-17-18-38-09/2015-10-19-10-27-29:
    id: 186
    hash: ''
    dropdown_hide: ''
    width: auto
    class: preset2
  2015-10-17-18-38-09/2015-10-19-10-28-00:
    id: 187
    hash: ''
    dropdown_hide: ''
    width: auto
    class: preset3
  2015-10-17-18-38-09/2015-10-19-10-28-30:
    id: 188
    hash: ''
    dropdown_hide: ''
    width: auto
    class: preset4
  2015-10-17-18-38-09/2015-10-19-10-28-57:
    id: 189
    hash: ''
    dropdown_hide: ''
    width: auto
    class: preset5
  2015-10-17-18-38-09/2015-10-19-10-29-22:
    id: 190
    hash: ''
    dropdown_hide: ''
    width: auto
    class: preset6
  __particle-KjbCK:
    type: particle
    particle: modal-search
    title: 'Modal Search'
    options:
      particle:
        enabled: '1'
        html: modal-search
        filter: '1'
      block:
        extra: {  }
  __particle-GWhqM:
    type: particle
    particle: offcanvas-toggle
    title: 'Offcanvas Toggle'
    options:
      particle:
        enabled: '1'
        icon: 'fa fa-bars'
      block:
        extra: {  }
