preset: preset2
base:
  background-color: '#ffffff'
  text-color: '#333333'
fonts:
  body-font: roboto
  heading-font: family=Patua+One
  menu-font: family=Patua+One
fontsizes:
  body-font-size: 16px
accent:
  color-1: '#8bc53f'
top:
  background-color: '#f8f9fa'
copyright:
  background-color: '#ffffff'
  background-attachment: scroll
  text-color: '#333333'
  heading-color: ''
breakpoints:
  large-desktop-container: 1170px
  desktop-container: 960px
  tablet-container: 768px
menu:
  animation: g-fade
