name: _body_only
timestamp: 1474625430
version: 7
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1445341936
positions: {  }
sections:
  main: Main
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-8921: Messages
  content:
    system-content-8827: 'Page Content'
inherit: {  }
