version: 2
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1445341936
layout:
  /main/:
    -
      - system-messages-8921
    -
      - system-content-8827
  offcanvas: {  }
structure:
  main:
    attributes:
      id: g-main
      boxed: ''
  offcanvas:
    attributes:
      id: g-offcanvas
content:
  system-messages-8921:
    title: Messages
