name: 15
timestamp: 1474625430
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1445341936
positions:
  drawer: Drawer
  top-a: Top-a
  top-b: Top-b
  top-c: Top-c
  top-d: Top-d
  navigation-a: Navigation-a
  navigation-b: Navigation-b
  navigation-c: Navigation-c
  navigation-d: Navigation-d
  breadcrumb-a: Breadcrumb-a
  breadcrumb-b: Breadcrumb-b
  breadcrumb-c: Breadcrumb-c
  breadcrumb-d: Breadcrumb-d
  fullwidth: Fullwidth
  showcase-a: Showcase-a
  showcase-b: Showcase-b
  showcase-c: Showcase-c
  showcase-d: Showcase-d
  intro-a: Intro-a
  intro-b: Intro-b
  intro-c: Intro-c
  intro-d: Intro-d
  feature-a: Feature-a
  feature-b: Feature-b
  feature-c: Feature-c
  feature-d: Feature-d
  subfeature-a: Subfeature-a
  subfeature-b: Subfeature-b
  subfeature-c: Subfeature-c
  subfeature-d: Subfeature-d
  utility-a: Utility-a
  utility-b: Utility-b
  utility-c: Utility-c
  utility-d: Utility-d
  maintop-a: Maintop-a
  maintop-b: Maintop-b
  maintop-c: Maintop-c
  maintop-d: Maintop-d
  sidebar-left: Sidebar-left
  content-top-a: Content-top-a
  content-top-b: Content-top-b
  content-bottom-a: Content-bottom-a
  content-bottom-b: Content-bottom-b
  sidebar-right: Sidebar-right
  mainbottom-a: Mainbottom-a
  mainbottom-b: Mainbottom-b
  mainbottom-c: Mainbottom-c
  mainbottom-d: Mainbottom-d
  extension-a: Extension-a
  extension-b: Extension-b
  extension-c: Extension-c
  extension-d: Extension-d
  additional-a: Additional-a
  additional-b: Additional-b
  additional-c: Additional-c
  additional-d: Additional-d
  prebottom-a: Prebottom-a
  prebottom-b: Prebottom-b
  prebottom-c: Prebottom-c
  prebottom-d: Prebottom-d
  bottom-a: Bottom-a
  bottom-b: Bottom-b
  bottom-c: Bottom-c
  bottom-d: Bottom-d
  afterbottom-a: Afterbottom-a
  afterbottom-b: Afterbottom-b
  afterbottom-c: Afterbottom-c
  afterbottom-d: Afterbottom-d
  last-a: Last-a
  last-b: Last-b
  last-c: Last-c
  last-d: Last-d
  footer-a: Footer-a
  footer-b: Footer-b
  footer-c: Footer-c
  footer-d: Footer-d
  copyright-a: Copyright-a
  copyright-b: Copyright-b
  copyright-c: Copyright-c
  copyright-d: Copyright-d
  offcanvas-a: Offcanvas-a
  offcanvas-b: Offcanvas-b
sections:
  drawer: Drawer
  top: Top
  navigation: Navigation
  breadcrumb: Breadcrumb
  fullwidth: Fullwidth
  showcase: Showcase
  intro: Intro
  feature: Feature
  subfeature: Subfeature
  utility: Utility
  maintop: Maintop
  system-messages: System-messages
  sidebar: Sidebar
  mainbody: Mainbody
  mainbottom: Mainbottom
  extension: Extension
  additional: Additional
  prebottom: Prebottom
  bottom: Bottom
  afterbottom: Afterbottom
  last: Last
  copyright: Copyright
  to-top: To-top
  header: Header
  aside: Aside
  footer: Footer
  offcanvas: Offcanvas
particles:
  position:
    position-drawer: Drawer
    position-top-a: Top-a
    position-top-b: Top-b
    position-top-c: Top-c
    position-top-d: Top-d
    position-navigation-a: Navigation-a
    position-navigation-b: Navigation-b
    position-navigation-c: Navigation-c
    position-navigation-d: Navigation-d
    position-breadcrumb-a: Breadcrumb-a
    position-breadcrumb-b: Breadcrumb-b
    position-breadcrumb-c: Breadcrumb-c
    position-breadcrumb-d: Breadcrumb-d
    position-fullwidth: Fullwidth
    position-showcase-a: Showcase-a
    position-showcase-b: Showcase-b
    position-showcase-c: Showcase-c
    position-showcase-d: Showcase-d
    position-intro-a: Intro-a
    position-intro-b: Intro-b
    position-intro-c: Intro-c
    position-intro-d: Intro-d
    position-feature-a: Feature-a
    position-feature-b: Feature-b
    position-feature-c: Feature-c
    position-feature-d: Feature-d
    position-subfeature-a: Subfeature-a
    position-subfeature-b: Subfeature-b
    position-subfeature-c: Subfeature-c
    position-subfeature-d: Subfeature-d
    position-utility-a: Utility-a
    position-utility-b: Utility-b
    position-utility-c: Utility-c
    position-utility-d: Utility-d
    position-maintop-a: Maintop-a
    position-maintop-b: Maintop-b
    position-maintop-c: Maintop-c
    position-maintop-d: Maintop-d
    position-sidebar-left: Sidebar-left
    position-content-top-a: Content-top-a
    position-content-top-b: Content-top-b
    position-content-bottom-a: Content-bottom-a
    position-content-bottom-b: Content-bottom-b
    position-sidebar-right: Sidebar-right
    position-mainbottom-a: Mainbottom-a
    position-mainbottom-b: Mainbottom-b
    position-mainbottom-c: Mainbottom-c
    position-mainbottom-d: Mainbottom-d
    position-extension-a: Extension-a
    position-extension-b: Extension-b
    position-extension-c: Extension-c
    position-extension-d: Extension-d
    position-additional-a: Additional-a
    position-additional-b: Additional-b
    position-additional-c: Additional-c
    position-additional-d: Additional-d
    position-prebottom-a: Prebottom-a
    position-prebottom-b: Prebottom-b
    position-prebottom-c: Prebottom-c
    position-prebottom-d: Prebottom-d
    position-bottom-a: Bottom-a
    position-bottom-b: Bottom-b
    position-bottom-c: Bottom-c
    position-bottom-d: Bottom-d
    position-afterbottom-a: Afterbottom-a
    position-afterbottom-b: Afterbottom-b
    position-afterbottom-c: Afterbottom-c
    position-afterbottom-d: Afterbottom-d
    position-last-a: Last-a
    position-last-b: Last-b
    position-last-c: Last-c
    position-last-d: Last-d
    position-footer-a: Footer-a
    position-footer-b: Footer-b
    position-footer-c: Footer-c
    position-footer-d: Footer-d
    position-copyright-a: Copyright-a
    position-copyright-b: Copyright-b
    position-copyright-c: Copyright-c
    position-copyright-d: Copyright-d
    position-offcanvas-a: Offcanvas-a
    position-offcanvas-b: Offcanvas-b
  logo:
    logo-4696: Logo
  menu:
    menu-2461: Menu
  messages:
    system-messages-6643: 'System Messages'
  content:
    system-content-4486: 'Page Content'
  totop:
    totop-5726: Totop
  mobile-menu:
    mobile-menu-2248: Mobile-menu
inherit: {  }
